FROM maven:3.9.4-eclipse-temurin-21 AS build

WORKDIR /app

COPY pom.xml .
COPY src ./src

COPY --from=common-config:/app/libs/common-config.jar /app/libs/
COPY --from=common-dto:/app/libs/common-dto.jar /app/libs/

RUN mvn clean package -DskipTests

FROM eclipse-temurin:21-jdk

WORKDIR /app

COPY --from=build /app/target/gateway-api.jar /app/libs/

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/libs/gateway-api.jar"]
